version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/myapp_development
    volumes:
      - "./:/usr/src/app"

  db:
    image: pgvector/pgvector:pg17 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: